export interface IAdoptant {
  id: number;
  documentId: string;
  name: string;
  firstName: string;
  email: string;
  password?: string | null;
  birthDate?: string | null;
  phone?: string | null;
  address?: string | null;
  postalCode?: string | null;
  city?: string | null;
  householdComposition?: string | null;
  roommatesCount?: number | null;
  hasChildren?: boolean | null;
  childrenCount?: number | null;
  childrenAges?: string | null;
  householdAgreement?: boolean | null;
  disagreementDetails?: string | null;
  workStatus?: string | null;
  profession?: string | null;
  workingHours?: string | null;
  aloneTime?: string | null;
  housingType: "maison" | "appartement" | "autre" | null;
  housingSurface?: string | null;
  livingEnvironment?: string | null;
  nearBusyRoad?: string | null;
  petCanGoOutside?: string | null;
  apartmentFloor?: number | null;
  windowsSecured?: string | null;
  planToSecureWindows?: string | null;
  hasGarden: string | null;
  gardenSurface?: string | null;
  gardenFenced?: string | null;
  fenceHeight?: string | null;
  hasBalconyOrTerrace?: string | null;
  balconySurface?: string | null;
  balconySecured?: string | null;
  hasOtherAnimals?: boolean | null;
  otherAnimalsDetails?: string | null;
  sterilizedAnimals?: boolean | null;
  petsSince?: string | null;
  remarks?: string | null;
  acceptsResponsibility?: boolean | null;
}
